#Extra methods created
from matrix_transpose import matrix_transpose
from convert_vec_mat import convert_vec_mat


#Methods created for class
from abs_error import abs_error
from dmaceps import calculate_double_float_precision
from gen_rand_matrix import gen_rand_matrix
from gen_sym_matrix import gen_sym_matrix
from rel_error import rel_error
from smaceps import calculate_single_float_precision
from vector_1norm import vector_1norm
from vector_2norm import vector_2norm
from vector_add import vector_add
from vector_infnorm import vector_infnorm
from vector_scal_mult import vector_scal_mult

from abs_error_2norm import abs_error_2norm
from abs_error_1norm import abs_error_1norm
from abs_error_infnorm import abs_error_infnorm
from matrix_1norm import matrix_1norm
from matrix_infnorm import matrix_infnorm
from vector_dot import vector_dot
from vector_cross import vector_cross
from matrix_mult import matrix_mult
from gen_diagdom_matrix import gen_diagdom_matrix

from matrix_scal_mult import matrix_scal_mult
from matrix_add import matrix_add
from matrix_outer import matrix_outer
from matrix_solve_diagonal import matrix_solve_diagonal
from matrix_solve_upper_tri import matrix_solve_upper_tri
from matrix_solve_lower_tri import matrix_solve_lower_tri
from matrix_ref import matrix_ref
from matrix_solve import matrix_solve
from gen_diagdom_sym_matrix import gen_diagdom_sym_matrix

from matrix_solve_least_square import matrix_solve_least_square
from matrix_LU_factor import matrix_LU_factor
from matrix_solve_LU import matrix_solve_LU
from gen_sym_posdef_matrix import gen_sym_posdef_matrix
from matrix_cholesky_fac import matrix_cholesky_fac
from matrix_solve_least_square_normal import matrix_solve_least_square_normal
from matrix_QR_factorization import matrix_QR_factorization
from hilbert_matrix_QR_test import hilbert_matrix_QR_test
from gen_sqr_diagdom_matrix import gen_sqr_diagdom_matrix


from matrix_solve_QR_factorization import matrix_solve_QR_factorization
from matrix_QR_factorization_mod import matrix_QR_factorization_mod
from matrix_QR_factorization_householder import matrix_QR_factorization_householder
from matrix_solve_least_squares_QR import matrix_solve_least_squares_QR
from matrix_solve_least_squares_QR_householder import matrix_solve_least_squares_QR_householder
from matrix_solve_jacobian import matrix_solve_jacobian
from matrix_solve_gauss_seidel import matrix_solve_gauss_seidel

from matrix_solve_steepest_descent import matrix_solve_steepest_descent
from matrix_solve_conjugate_gradient import matrix_solve_conjugate_gradient
from matrix_solve_jacobian_smart import matrix_solve_jacobian_smart

from matrix_power_iteration import matrix_power_iteration
from matrix_inverse_power_iteration import matrix_inverse_power_iteration
from matrix_condition_number import matrix_condition_number
from matrix_rayleigh_quotient_iteration import matrix_rayleigh_quotient_iteration